AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

  AlarmSNSTopicArn:
    Type: String

  CdcPnActionShards:
    Type: Number
    Default: 12
    Description: Number of shards for the stream CdcPnActionShards, 0 for OnDemand

  CdcPnActionStreamRetentionHours:
    Type: Number
    Default: 168
    Description: Number of hours to retain data records in the stream

  CdcActionStandardAlarmThresholdsMs:
    Type: Number
    Default: 2000000
    Description: Threshold for standard alarms in milliseconds

  CdcActionOnCallAlarmThresholdsMs:
    Type: Number
    Default: 2000000
    Description: Threshold for oncall alarms in milliseconds for pn-<xx>Action tables

  ## KINESIS STREAM PARAMS USED FOR NEW kinesis-data-stream.yml fragment template
  CdcPnFutureActionShards:
    Type: Number
    Default: 8
    Description: Number of shards for the stream CdcPnFutureAction, 0 for OnDemand

  CdcPnFutureActionStreamRetentionHours:
    Type: Number
    Default: 168
    Description: Number of hours to retain data records in the stream

Resources:
  PnActionManagerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-action-manager'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

  ActionRouterManagerDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-action_manager_action_router_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"

  ActionEnqueuerManagerDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-action_manager_action_enqueuer_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"

  ActionTimeoutErrorDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-action_manager_action-timeout-error-DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"

  # Action Table
  ActionTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-Action'
      AttributeDefinitions:
        - AttributeName: "actionId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "actionId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "iun-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !GetAtt CdcPnActionStream.Outputs.KinesisStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Future Action Table
  FutureActionTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-FutureAction'
      AttributeDefinitions:
        - AttributeName: "timeSlot"
          AttributeType: "S"
        - AttributeName: "actionId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "timeSlot"
          KeyType: "HASH"
        - AttributeName: "actionId"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "iun-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !GetAtt CdcPnFutureActionStream.Outputs.KinesisStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Last scheduled poll time
  LastPollForFutureActionTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-LastPollForFutureActionTable'
      AttributeDefinitions:
        - AttributeName: "lastPoolKey"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "lastPoolKey"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ### Kinesis Data Stream: CDC for PN-ACTION DynamoDB Table (INSERT CDC ARE THE INTERESTED ONE)
  CdcPnActionStream:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-data-stream.yaml"
      Parameters:
        StreamName: "pn-action-cdc"
        # PROVISIONED MODE: follow shard configuration
        StreamShardsCount: !Ref CdcPnActionShards
        StreamRetentionHours: !Ref CdcPnActionStreamRetentionHours
        RequireManagedKey: false
        # USES SNSTopic used for all Kinesis alarms
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        StandardAlarmThresholdsMs: !Ref CdcActionStandardAlarmThresholdsMs
        OnCallAlarmThresholdsMs: !Ref CdcActionOnCallAlarmThresholdsMs

  ### Kinesis Data Stream: CDC for PN-FUTURE-ACTION DynamoDB Table
  CdcPnFutureActionStream:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-data-stream.yaml"
      Parameters:
        StreamName: "pn-future-action-cdc"
        # PROVISIONED MODE: follow shard configuration
        StreamShardsCount: !Ref CdcPnFutureActionShards
        StreamRetentionHours: !Ref CdcPnFutureActionStreamRetentionHours
        RequireManagedKey: false
        # USES SNSTopic used for all Kinesis alarms
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        StandardAlarmThresholdsMs: !Ref CdcActionStandardAlarmThresholdsMs
        OnCallAlarmThresholdsMs: !Ref CdcActionOnCallAlarmThresholdsMs

Outputs:
  EcsLogGroup:
    Value: !GetAtt PnActionManagerLogGroup.Outputs.LogGroupName

  ActionRouterManagerLambdaName:
    Value: !Sub "${ProjectName}-actionRouterLambda-manager"

  ActionEnqueuerManagerLambdaName:
    Value: !Sub "${ProjectName}-actionEnqueuer-manager"

  ActionRemoverManagerLambdaName:
    Value: !Sub "${ProjectName}-actionRemover-manager"

  ActionRouterManagerDLQARN:
    Value: !GetAtt ActionRouterManagerDLQ.Outputs.QueueARN
    Description: ActionRouterManagerDLQ queue ARN
  ActionRouterManagerAlarmARN:
    Value: !GetAtt ActionRouterManagerDLQ.Outputs.SqsDLQAlarmArn
    Description: ActionRouterManagerDLQ alarm ARN

  ActionEnqueuerManagerDLQARN:
    Value: !GetAtt ActionEnqueuerManagerDLQ.Outputs.QueueARN
    Description: ActionEnqueuerManagerDLQ queue ARN
  ActionEnqueuerManagerDLQAlarmARN:
    Value: !GetAtt ActionEnqueuerManagerDLQ.Outputs.SqsDLQAlarmArn
    Description: ActionEnqueuerManagerDLQ alarm ARN

  ActionTimeoutErrorDLQARN:
    Value: !GetAtt ActionTimeoutErrorDLQ.Outputs.QueueARN
    Description: ActionTimeoutErrorDLQ queue ARN
  ActionTimeoutErrorDLQAlarmARN:
    Value: !GetAtt ActionTimeoutErrorDLQ.Outputs.SqsDLQAlarmArn
    Description: ActionTimeoutErrorDLQ alarm ARN
  ActionTimeoutErrorDLQURL:
    Value: !GetAtt ActionTimeoutErrorDLQ.Outputs.QueueURL
    Description: ActionTimeoutErrorDLQ queue URL

  ActionDynamoTableName:
    Description: Name of dynamodb table containing
    Value: !Ref ActionTable
  ActionDynamoTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${ActionTable.Arn}'

  FutureActionDynamoTableName:
    Description: Name of dynamodb table containing
    Value: !Ref FutureActionTable
  FutureActionDynamoTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${FutureActionTable.Arn}'

  LastPollForFutureActionDynamoTableName:
    Description: Name of dynamodb table containing
    Value: !Ref LastPollForFutureActionTable
  LastPollForFutureActionDynamoTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${LastPollForFutureActionTable.Arn}'

  CdcPnActionArn:
    Value: !GetAtt CdcPnActionStream.Outputs.KinesisStreamArn
    Description: "Kinesis source stream name ARN"

  CdcPnFutureActionArn:
    Value: !GetAtt CdcPnFutureActionStream.Outputs.KinesisStreamArn
    Description: "Kinesis source stream name ARN"