AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

Resources:
  ActionRouterDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_action_router_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"

  ActionEnqueuerDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_action_enqueuer_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"

  ActionTimeoutErrorDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_action-timeout-error-DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"


Outputs:
  ActionRouterLambdaName:
    Value: !Sub "${ProjectName}-actionRouterLambda-manager"

  ActionEnqueuerLambdaName:
    Value: !Sub "${ProjectName}-actionEnqueuer-manager"

  ActionRemoverLambdaName:
    Value: !Sub "${ProjectName}-actionRemover-manager"

  ActionRouterDLQARN:
    Value: !GetAtt ActionRouterDLQ.Outputs.QueueARN
    Description: ActionRouterDLQ queue ARN
  ActionRouterDLQAlarmARN:
    Value: !GetAtt ActionRouterDLQ.Outputs.SqsDLQAlarmArn
    Description: ActionRouterDLQ alarm ARN

  ActionEnqueuerDLQARN:
    Value: !GetAtt ActionEnqueuerDLQ.Outputs.QueueARN
    Description: ActionEnqueuerDLQ queue ARN
  ActionEnqueuerDLQAlarmARN:
    Value: !GetAtt ActionEnqueuerDLQ.Outputs.SqsDLQAlarmArn
    Description: ActionEnqueuerDLQ alarm ARN

  ActionTimeoutErrorDLQARN:
    Value: !GetAtt ActionTimeoutErrorDLQ.Outputs.QueueARN
    Description: ActionTimeoutErrorDLQ queue ARN
  ActionTimeoutErrorDLQAlarmARN:
    Value: !GetAtt ActionTimeoutErrorDLQ.Outputs.SqsDLQAlarmArn
    Description: ActionTimeoutErrorDLQ alarm ARN

