package it.pagopa.pn.actionmanager.dto.action;

import lombok.Getter;

@Getter
public enum ActionType {

    NOTIFICATION_VALIDATION,

    NOTIFICATION_REFUSED,

    NOTIFICATION_CANCELLATION,

    SCHEDULE_RECEIVED_LEGALFACT_GENERATION,

    CHECK_ATTACHMENT_RETENTION,

    START_RECIPIENT_WORKFLOW,

    CHOOSE_DELIVERY_MODE,

    ANALOG_WORKFLOW,

    DIGITAL_WORKFLOW_NEXT_ACTION,

    DIGITAL_WORKFLOW_NEXT_EXECUTE_ACTION,

    DIGITAL_WORKFLOW_NO_RESPONSE_TIMEOUT_ACTION,

    DIGITAL_WORKFLOW_RETRY_ACTION,

    SEND_DIGITAL_FINAL_STATUS_RESPONSE,

    REFINEMENT_NOTIFICATION,

    SENDER_ACK,

    DOCUMENT_CREATION_RESPONSE,

    POST_ACCEPTED_PROCESSING_COMPLETED,

    SEND_ANALOG_FINAL_STATUS_RESPONSE,

    ANALOG_WORKFLOW_NO_FEEDBACK_TIMEOUT,

    NOTIFICATION_REWORK_VALIDATION,

    NOTIFICATION_REWORK_REQUESTED,

    NOTIFICATION_REWORK_UPDATE;

}
